version: '3.8'

services:
  api:
    image: redis-pub/sub:latest
    ports: 
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      
  redis:
    image: redis